title: Sami Abdurahman - Academic Website
description: PhD Candidate in Economics at TMU
page-top-title: Sami Abdurahman
top-section-bg-text: 
home-subtitle: 
copyright-text: '&copy; Sami Abdurahman 2026. All Rights Reserved.'
